# Global variables
GRID_SIZE = 12

# Tile settings
TILE_SIZE = 70
TILE_PADDING = 5

# Screen settings
SCSREEN_WIDTH = GRID_SIZE * (2 * TILE_PADDING + TILE_SIZE)
SCSREEN_HEIGHT = GRID_SIZE * (2 * TILE_PADDING + TILE_SIZE)
SCREEN_SIZE = (SCSREEN_WIDTH, SCSREEN_HEIGHT)

# Fps value
FPS_VALUE = 60

# Colors 
DARK_GREEN = (35, 74, 16)


# --- REWARD SHAPING ---
STEP_COST = -0.04
REVISIT_PENALTY = -0.12
WALL_PENALTY = -0.05
LOOP_PENALTY = -0.25
LAMBDA = 1.0
BETA = 2.2

HIDER_LOCATIONS = [
    (1, 7),
    (8, 2),
    (9, 9),
]

GOAL_REWARDS = {pos: 10.0 for pos in HIDER_LOCATIONS}